/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlunosRouteImport } from './routes/alunos'
import { Route as CaptacaoRouteImport } from './routes/captacao'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as RetencaoRouteImport } from './routes/retencao'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as TurmasRouteImport } from './routes/turmas'
import { Route as AdminModulosRouteImport } from './routes/admin/modulos'
import { Route as AdminPerfilRouteImport } from './routes/admin/perfil'
import { Route as AdminUsuariosRouteImport } from './routes/admin/usuarios'
import { Route as PortalAlunoRouteImport } from './routes/portal/aluno'
import { Route as PublicPreMatriculaRouteImport } from './routes/public/pre-matricula'
import { Route as PublicTesteNivelRouteImport } from './routes/public/teste-nivel'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunosRoute = AlunosRouteImport.update({
  id: '/alunos',
  path: '/alunos',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptacaoRoute = CaptacaoRouteImport.update({
  id: '/captacao',
  path: '/captacao',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const RetencaoRoute = RetencaoRouteImport.update({
  id: '/retencao',
  path: '/retencao',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const TurmasRoute = TurmasRouteImport.update({
  id: '/turmas',
  path: '/turmas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminModulosRoute = AdminModulosRouteImport.update({
  id: '/admin/modulos',
  path: '/admin/modulos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPerfilRoute = AdminPerfilRouteImport.update({
  id: '/admin/perfil',
  path: '/admin/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/admin/usuarios',
  path: '/admin/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalAlunoRoute = PortalAlunoRouteImport.update({
  id: '/portal/aluno',
  path: '/portal/aluno',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicPreMatriculaRoute = PublicPreMatriculaRouteImport.update({
  id: '/public/pre-matricula',
  path: '/public/pre-matricula',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicTesteNivelRoute = PublicTesteNivelRouteImport.update({
  id: '/public/teste-nivel',
  path: '/public/teste-nivel',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alunos': typeof AlunosRoute
  '/captacao': typeof CaptacaoRoute
  '/crm': typeof CrmRoute
  '/financeiro': typeof FinanceiroRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/retencao': typeof RetencaoRoute
  '/super-admin': typeof SuperAdminRoute
  '/turmas': typeof TurmasRoute
  '/admin/modulos': typeof AdminModulosRoute
  '/admin/perfil': typeof AdminPerfilRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/portal/aluno': typeof PortalAlunoRoute
  '/public/pre-matricula': typeof PublicPreMatriculaRoute
  '/public/teste-nivel': typeof PublicTesteNivelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alunos': typeof AlunosRoute
  '/captacao': typeof CaptacaoRoute
  '/crm': typeof CrmRoute
  '/financeiro': typeof FinanceiroRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/retencao': typeof RetencaoRoute
  '/super-admin': typeof SuperAdminRoute
  '/turmas': typeof TurmasRoute
  '/admin/modulos': typeof AdminModulosRoute
  '/admin/perfil': typeof AdminPerfilRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/portal/aluno': typeof PortalAlunoRoute
  '/public/pre-matricula': typeof PublicPreMatriculaRoute
  '/public/teste-nivel': typeof PublicTesteNivelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alunos': typeof AlunosRoute
  '/captacao': typeof CaptacaoRoute
  '/crm': typeof CrmRoute
  '/financeiro': typeof FinanceiroRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/retencao': typeof RetencaoRoute
  '/super-admin': typeof SuperAdminRoute
  '/turmas': typeof TurmasRoute
  '/admin/modulos': typeof AdminModulosRoute
  '/admin/perfil': typeof AdminPerfilRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/portal/aluno': typeof PortalAlunoRoute
  '/public/pre-matricula': typeof PublicPreMatriculaRoute
  '/public/teste-nivel': typeof PublicTesteNivelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alunos'
    | '/captacao'
    | '/crm'
    | '/financeiro'
    | '/leads'
    | '/login'
    | '/manager'
    | '/retencao'
    | '/super-admin'
    | '/turmas'
    | '/admin/modulos'
    | '/admin/perfil'
    | '/admin/usuarios'
    | '/portal/aluno'
    | '/public/pre-matricula'
    | '/public/teste-nivel'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alunos'
    | '/captacao'
    | '/crm'
    | '/financeiro'
    | '/leads'
    | '/login'
    | '/manager'
    | '/retencao'
    | '/super-admin'
    | '/turmas'
    | '/admin/modulos'
    | '/admin/perfil'
    | '/admin/usuarios'
    | '/portal/aluno'
    | '/public/pre-matricula'
    | '/public/teste-nivel'
  id:
    | '__root__'
    | '/'
    | '/alunos'
    | '/captacao'
    | '/crm'
    | '/financeiro'
    | '/leads'
    | '/login'
    | '/manager'
    | '/retencao'
    | '/super-admin'
    | '/turmas'
    | '/admin/modulos'
    | '/admin/perfil'
    | '/admin/usuarios'
    | '/portal/aluno'
    | '/public/pre-matricula'
    | '/public/teste-nivel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlunosRoute: typeof AlunosRoute
  CaptacaoRoute: typeof CaptacaoRoute
  CrmRoute: typeof CrmRoute
  FinanceiroRoute: typeof FinanceiroRoute
  LeadsRoute: typeof LeadsRoute
  LoginRoute: typeof LoginRoute
  ManagerRoute: typeof ManagerRoute
  RetencaoRoute: typeof RetencaoRoute
  SuperAdminRoute: typeof SuperAdminRoute
  TurmasRoute: typeof TurmasRoute
  AdminModulosRoute: typeof AdminModulosRoute
  AdminPerfilRoute: typeof AdminPerfilRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  PortalAlunoRoute: typeof PortalAlunoRoute
  PublicPreMatriculaRoute: typeof PublicPreMatriculaRoute
  PublicTesteNivelRoute: typeof PublicTesteNivelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alunos': {
      id: '/alunos'
      path: '/alunos'
      fullPath: '/alunos'
      preLoaderRoute: typeof AlunosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captacao': {
      id: '/captacao'
      path: '/captacao'
      fullPath: '/captacao'
      preLoaderRoute: typeof CaptacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retencao': {
      id: '/retencao'
      path: '/retencao'
      fullPath: '/retencao'
      preLoaderRoute: typeof RetencaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/turmas': {
      id: '/turmas'
      path: '/turmas'
      fullPath: '/turmas'
      preLoaderRoute: typeof TurmasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/modulos': {
      id: '/admin/modulos'
      path: '/admin/modulos'
      fullPath: '/admin/modulos'
      preLoaderRoute: typeof AdminModulosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/perfil': {
      id: '/admin/perfil'
      path: '/admin/perfil'
      fullPath: '/admin/perfil'
      preLoaderRoute: typeof AdminPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/aluno': {
      id: '/portal/aluno'
      path: '/portal/aluno'
      fullPath: '/portal/aluno'
      preLoaderRoute: typeof PortalAlunoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public/pre-matricula': {
      id: '/public/pre-matricula'
      path: '/public/pre-matricula'
      fullPath: '/public/pre-matricula'
      preLoaderRoute: typeof PublicPreMatriculaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public/teste-nivel': {
      id: '/public/teste-nivel'
      path: '/public/teste-nivel'
      fullPath: '/public/teste-nivel'
      preLoaderRoute: typeof PublicTesteNivelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlunosRoute: AlunosRoute,
  CaptacaoRoute: CaptacaoRoute,
  CrmRoute: CrmRoute,
  FinanceiroRoute: FinanceiroRoute,
  LeadsRoute: LeadsRoute,
  LoginRoute: LoginRoute,
  ManagerRoute: ManagerRoute,
  RetencaoRoute: RetencaoRoute,
  SuperAdminRoute: SuperAdminRoute,
  TurmasRoute: TurmasRoute,
  AdminModulosRoute: AdminModulosRoute,
  AdminPerfilRoute: AdminPerfilRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  PortalAlunoRoute: PortalAlunoRoute,
  PublicPreMatriculaRoute: PublicPreMatriculaRoute,
  PublicTesteNivelRoute: PublicTesteNivelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
